use proc_macro::TokenStream;

#[proc_macro]
pub fn make_answer(_input: TokenStream) -> TokenStream {
    "42".parse().unwrap()
}

#[proc_macro]
pub fn make_function(input: TokenStream) -> TokenStream {
    let function_name = input.to_string();
    let generated_code = format!(
        r#"
        fn {function_name}() -> &'static str {{
            "this function was generated by make_function!"
        }}
        "#
    );

    generated_code.parse().unwrap()
}

#[proc_macro_attribute]
pub fn add_generated_helper(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut generated_code = item.to_string();
    generated_code.push_str(
        r#"

        fn generated_helper() -> &'static str {
            "this helper was generated by add_generated_helper"
        }
        "#,
    );

    generated_code.parse().unwrap()
}
